/*
 * Universal Video Player v2.4.3
 *
 * Copyright 2014-2017, LambertGroup
 *
*/


(function(c){function W(a,b,f){f.css({background:a.playlistRecordBgOffColor});a.playlistRecordShowTitle?c(".title",f).css({color:a.playlistRecordTitleOffColor}):c(".title",f).css({display:"none"});a.playlistRecordShowDesc?c(".reg",f).css({color:a.playlistRecordDescOffColor}):c(".reg",f).css({display:"none"});b=f.find("img:first");a.playlistRecordShowImg?b.css({opacity:a.playlistRecordBgOffImgOpacity/100,filter:"alpha(opacity="+a.playlistRecordBgOffImgOpacity+")"}):b.css({display:"none"})}function X(a,
b,f){f.css({background:a.playlistRecordBgOnColor});c(".title",f).css({color:a.playlistRecordTitleOnColor});c(".reg",f).css({color:a.playlistRecordDescOnColor});f.find("img:first").css({opacity:a.playlistRecordBgOnImgOpacity/100,filter:"alpha(opacity="+a.playlistRecordBgOnImgOpacity+")"})}function ba(a,b,f,g,h,e,n,l,p,k,m,q,A,u,x){var v=!0,E="next",w=f.shuffle;-1==a&&(E="previous");b.thumbsClicked&&(w=!1);if(!f.loop&&b.current_img_no+a>=b.selectedCateg_total_images||!f.loop&&0>b.current_img_no+a||
b.categsAreListed)v=!1;v&&(W(f,b,c(b.thumbsHolder_Thumbs[b.current_img_no])),ta(b,f,g,x),a=E,w?(w=Math.floor(Math.random()*(b.selectedCateg_total_images-1)),b.current_img_no=w!=b.current_img_no?w:Math.floor(Math.random()*(b.selectedCateg_total_images-1))):"next"==a?b.current_img_no==b.selectedCateg_total_images-1?b.current_img_no=0:b.current_img_no++:0>b.current_img_no-1?b.current_img_no=b.selectedCateg_total_images-1:b.current_img_no--,b.origID=c("div[rel='"+b.current_img_no+"']").attr("data-origID"),
b.previousOrigID=b.origID,b.currentImg=b.playlist_arr[b.origID],e.html(b.playlist_arr[b.origID].title),b.thumbsClicked=!1,X(f,b,c(b.thumbsHolder_Thumbs[b.current_img_no])),ca(0,h,f,b),ja(b,f,m),void 0!=b.currentImg.youtube&&""!=b.currentImg.youtube||void 0!=b.currentImg.vimeo&&""!=b.currentImg.vimeo||void 0!=b.currentImg.selfhostedMP4&&""!=b.currentImg.selfhostedMP4)&&(f.autoPlayFirstVideo=!0,k.hasClass("pauseBut")||k.addClass("pauseBut"),Q(b,b.origID)&&(b.youtubeWasStarted=-1,g.css("background",
"#000000"),-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?(b.player.cueVideoById(b.playlist_arr[b.origID].youtube),k.removeClass("pauseBut")):b.player.loadVideoById(b.playlist_arr[b.origID].youtube,0,f.suggestedQuality),b.player.setVolume(100*f.initialVolume),c(".lbg_player",g).css({"z-index":4}),da(b,f,g,n,l,q,"block"),f.googleTrakingOn&&ga("send","event",b.googleYouTubeCateg,"Play","Title: "+b.playlist_arr[b.origID].title+
"  ---  ID: "+b.playlist_arr[b.origID].youtube)),T(b,b.origID)&&(g.css("background","#000000"),c("#"+x).attr("src","//player.vimeo.com/video/"+b.playlist_arr[b.origID].vimeo+"?api=1&amp;player_id="+x),da(b,f,g,n,l,q,"none"),m.css({display:"none"}),f.googleTrakingOn&&ga("send","event",b.googleVimeoCateg,"Play","Title: "+b.playlist_arr[b.origID].title+"  ---  ID: "+b.playlist_arr[b.origID].vimeo)),ea(b,b.origID)&&(h=fa(),g.css("background","#000000"),e=new Date,document.getElementById(b.html5_video_id).src=
oa(h,b,b.html5_video_id)+"?time="+e.getTime(),document.getElementById(b.html5_video_id).load(),c("#"+b.html5_video_id).css({"z-index":4,width:"100%",height:"100%"}),document.getElementById(b.html5_video_id).volume=f.initialVolume,document.getElementById(b.html5_video_id).play(),da(b,f,g,n,l,q,"block"),f.googleTrakingOn&&ga("send","event",b.googleSelfHostedCateg,"Play","Title: "+b.playlist_arr[b.origID].title+"  ---  ID: "+b.playlist_arr[b.origID].selfhostedMP4)),pa(b,f,g,n,l,q,p,m,x),b.videoIsFullScreen&&
f.showPlaylistBut&&(A.css({display:"none"}),u.css({left:parseInt(u.css("left").substr(0,u.css("left").lastIndexOf("px")),10)-A.width()-b.buttonsDistance+"px"})))}function ca(a,b,c,g){if(g.selectedCateg_total_images>c.numberOfThumbsPerScreen){c=(g.thumbsHolder_Thumb.height()+g.thumbMarginTop)*(g.selectedCateg_total_images-c.numberOfThumbsPerScreen);var f=0;b.stop(!0,!0);a&&!g.isCarouselScrolling?(g.isCarouselScrolling=!0,1>=a&&(a=0),f=parseInt(c*(a-100)/100,10),0<f&&(f=0),b.animate({top:f+"px"},1100,
"easeOutQuad",function(){g.isCarouselScrolling=!1})):g.isCarouselScrolling||(g.isCarouselScrolling=!0,b.css("opacity","0.5"),f=parseInt(-(g.thumbsHolder_Thumb.height()+g.thumbMarginTop)*g.current_img_no,10),Math.abs(f)>c&&(f=-c),g.universal_video_player_sliderVertical.slider("value",100+parseInt(100*f/c,10)),b.animate({opacity:1,top:f+"px"},500,"easeOutCubic",function(){g.isCarouselScrolling=!1}))}}function qa(a,b,f,g,h,e,n,l,p,k){if(a.categsAreListed||""==a.thumbsHolder_Thumbs)k.click();else{k=0;
b.origWidth!=b.width&&(k=2*b.borderWidth);l=c(".thumbsHolder_ThumbOFF .title",f);p=c(".thumbsHolder_ThumbOFF .reg",f);n=c(".thumbsHolder_ThumbOFF .padding",f);a.thumbsHolder_Thumbs.css({height:parseInt(h.height()/b.numberOfThumbsPerScreen,10)+"px"});n.css({"padding-left":parseInt(b.origthumbLeftPadding/(b.origWidth/(b.width-k)),10)+"px","padding-right":parseInt(b.origthumbRightPadding/(b.origWidth/(b.width-k)),10)+"px","padding-top":parseInt(b.origthumbTopPadding/(b.origWidth/(b.width-k)),10)+"px",
"padding-bottom":parseInt(b.origthumbBottomPadding/(b.origWidth/(b.width-k)),10)+"px"});h="px";-1!=l.css("font-size").lastIndexOf("em")&&(h="em");n="px";-1!=l.css("line-height").lastIndexOf("em")&&(n="em");l.css({"font-size":parseInt(b.origthumbTitleFont/(b.origWidth/(b.width-k)),10)+h,"line-height":parseInt(b.origthumbTitleLineHeight/(b.origWidth/(b.width-k)),10)+n});h="px";-1!=p.css("font-size").lastIndexOf("em")&&(h="em");n="px";-1!=p.css("line-height").lastIndexOf("em")&&(n="em");p.css({"font-size":parseInt(b.origthumbRegFont/
(b.origWidth/(b.width-k)),10)+h,"line-height":parseInt(b.origthumbRegLineHeight/(b.origWidth/(b.width-k)),10)+n});b.playlistRecordShowImg&&(f=c(".thumbsHolder_ThumbOFF",f).find("img:first"),!b.playlistRecordShowTitle&&!b.playlistRecordShowDesc||b.origWidth==b.width?b.playlistRecordShowTitle||b.playlistRecordShowDesc?f.css({width:parseInt(b.origThumbImgW/(b.origWidth/b.width),10)+"px",height:parseInt(b.origThumbImgH/(b.origWidth/b.width),10)+"px"}):f.css({width:parseInt(b.origThumbImgW/(b.origWidth/
b.width),10)+1+"px",height:a.thumbsHolder_Thumbs.height()+"px"}):f.css({width:parseInt(b.origThumbImgW/(b.origWidth/(b.width-42)),10)+"px",height:parseInt(b.origThumbImgH/(b.origWidth/(b.width-42)),10)+"px"}));var m=0,q=0;a.categsAreListed||(a.thumbMarginTop=Math.floor((e.height()-a.thumbsHolder_Thumb.height()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1)));thumb_i=0;g.children().each(function(){thumb_i++;theThumb=c(this);q=theThumb.height();1>=thumb_i?(m=Math.floor((e.height()-(a.thumbMarginTop+
theThumb.height())*(b.numberOfThumbsPerScreen-1)-theThumb.height())/2),1<=m&&(m=0),theThumb.css("margin-top",m+"px"),theThumb.height(q)):theThumb.css("margin-top",a.thumbMarginTop+"px")})}}function ka(a,b,f,g){c(".fullscreenVimeoButton",b).css({right:"82px"});374>=g&&c(".fullscreenVimeoButton",b).css({right:"37px"});305>=g&&c(".fullscreenVimeoButton",b).css({right:"5px"})}function la(a,b,f,g,h,e,n,l,p,k,m,q,A,u,x,v,E,w,D,G,t,J,K,N,M,L,F,H,C,z,B,R,O){if(!a.videoIsFullScreen)fa(),f=0,responsiveWidth=
g.parent().parent().parent().width(),responsiveHeight=g.parent().parent().parent().height(),b.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height()),b.width100Proc&&(b.width=responsiveWidth),b.height100Proc&&(b.height=responsiveHeight),b.origWidth>responsiveWidth||b.width100Proc?b.width=responsiveWidth:b.width100Proc||(b.width=b.origWidth),b.height100Proc||(b.height=b.width/a.playerRatio),b.width=parseInt(b.width,10),b.height=parseInt(b.height,10),n.width(b.width),
n.height(b.height),a.new_width=parseInt(b.width-b.playlistWidth/(b.origWidth/b.width)-3*b.borderWidth,10),a.new_height=b.height-2*b.borderWidth,b.playlistVisible||(a.new_width=parseInt(b.width-0-2*b.borderWidth,10)),e.width(a.new_width),e.height(a.new_height),e.css({left:b.borderWidth+"px",top:b.borderWidth+"px"}),c(".lbg_player",e).width(a.new_width),c(".lbg_player",e).height(a.new_height),c(".lbg_vimeo_player",e).width(a.new_width),c(".lbg_vimeo_player",e).height(a.new_height),ka(a,e,k,a.new_width),
p.width(b.playlistWidth/(b.origWidth/b.width)),p.height(a.new_height),k.width(b.playlistWidth/(b.origWidth/b.width)),k.height(a.new_height),k.css({top:0,right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px"}),l.width(b.playlistWidth/(b.origWidth/b.width)),l.css("top","0px"),a.selectedCateg_total_images>b.numberOfThumbsPerScreen&&(0>=b.borderWidth&&(f=a.universal_video_player_sliderVertical.width()/2),a.universal_video_player_sliderVertical.height(k.height()-15),a.universal_video_player_sliderVertical.css({display:"block",
left:Math.floor(b.width-2*b.borderWidth+(b.borderWidth-a.universal_video_player_sliderVertical.width())/2)-f+"px"})),b.showCategs&&(u.css({width:b.playlistWidth/(b.origWidth/b.width)+"px",right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px"}),x.css({"background-position":b.playlistWidth/(b.origWidth/b.width)-9+"px 50%"})),g="block",b.playlistVisible||(g="none"),b.showSearch&&(b.width<=a.minimalWidthSearch&&(g="none"),v.css({width:b.playlistWidth/(b.origWidth/b.width)+"px",top:3+(b.height-
2*b.borderWidth)+"px",right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px",display:g}),E.css({width:parseInt(b.playlistWidth/(b.origWidth/b.width),10)-100+"px"})),b.showLogo&&(v=c(".yourLogo",e).find("img:first"),v.css({"max-width":parseInt(100*b.width/b.origWidth,10)+"%"}),g="block",b.width<=a.minimalWidthSearch&&(g="none"),c(".yourLogo",e).css({display:g})),b.playlistVisible?(b.showNextPrevBut&&(F.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px"}),H.css({right:-1*
(b.borderWidth+b.playlistWidth/(b.origWidth/b.width)-F.width()-a.buttonsDistanceSeekBar)+"px"})),b.showShuffleBut&&C.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width)-F.width()-H.width()-a.totalButtonsDistanceSeekBar)+"px"})):(b.showNextPrevBut&&(F.css({right:0}),H.css({right:F.width()+a.buttonsDistanceSeekBar+"px"})),b.showShuffleBut&&C.css({right:F.width()+H.width()+a.totalButtonsDistanceSeekBar+"px"})),b.width<=a.minimalWidthInfo?U(a,b,e,w,D,G,t,J,K,N,M,L,!1,!1):b.width<=a.minimalWidthDownload?
U(a,b,e,w,D,G,t,J,K,N,M,L,!1,!0):U(a,b,e,w,D,G,t,J,K,N,M,L,!0,!0),T(a,a.origID)&&da(a,b,e,z,B,R,"none"),qa(a,b,e,l,p,k,m,q,A,u);else if(-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))L.click(),la(a,b,f,g,h,e,n,l,p,k,m,q,A,u,x,v,E,w,D,G,t,J,K,N,M,L,F,H,C,z,B,R,O);ca(0,l,b,a)}function fa(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,c=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=
c.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,c=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=c.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function oa(a,b,c){var f=b.playlist_arr[b.origID].selfhostedWEBM,h=navigator.userAgent.toLowerCase();if(-1!=h.indexOf("chrome")||-1!=h.indexOf("msie")||-1!=h.indexOf("safari")||-1!=h.indexOf("android"))f=b.playlist_arr[b.origID].selfhostedMP4;if(-1!=h.indexOf("ipad")||-1!=h.indexOf("iphone")||-1!=h.indexOf("ipod")||
-1!=h.indexOf("webos"))f=b.playlist_arr[b.origID].selfhostedMP4;-1!=h.indexOf("android")&&(f=b.playlist_arr[b.origID].selfhostedMP4);-1!=a&&(f=b.playlist_arr[b.origID].selfhostedMP4);-1!=h.indexOf("opera")&&(f=b.playlist_arr[b.origID].selfhostedWEBM,""!=ma(c)&&(f=b.playlist_arr[b.origID].selfhostedMP4));-1!=h.indexOf("opr/")&&(f=b.playlist_arr[b.origID].selfhostedWEBM,""!=ma(c)&&(f=b.playlist_arr[b.origID].selfhostedMP4));if(-1!=h.indexOf("firefox")||-1!=h.indexOf("mozzila"))f=b.playlist_arr[b.origID].selfhostedWEBM,
""!=ma(c)&&(f=b.playlist_arr[b.origID].selfhostedMP4);return f}function Q(a,b){var c=!1;void 0!=a.playlist_arr[b].youtube&&""!=a.playlist_arr[b].youtube&&a.haveYouTube&&(c=!0);return c}function T(a,b){var c=!1;void 0!=a.playlist_arr[b].vimeo&&""!=a.playlist_arr[b].vimeo&&a.haveVimeo&&(c=!0);return c}function ea(a,b){var c=!1;void 0!=a.playlist_arr[b].selfhostedMP4&&""!=a.playlist_arr[b].selfhostedMP4&&a.haveSelfHosted&&(c=!0);return c}function S(a){var b=10>Math.floor(a/60)?"0"+Math.floor(a/60):Math.floor(a/
60);return b+":"+(10>Math.floor(a-60*b)?"0"+Math.floor(a-60*b):Math.floor(a-60*b))}function pa(a,b,f,g,h,e,n,l,p){clearInterval(a.youTubeInterval);clearInterval(a.vimeoInterval);clearInterval(a.selfHostedInterval);a.totalTime=0;a.curTime=0;b.isBufferInitialized&&(g.progressbar("destroy"),b.isBufferInitialized=!1);b.isSeekBarInitialized&&(h.slider("destroy"),b.isSeekBarInitialized=!1);a.bufferedTime=0;g.css({background:b.bufferEmptyColor});T(a,a.origID)||(g.progressbar({value:0,complete:function(){a.is_buffer_complete=
!0},create:function(a,c){b.isBufferInitialized=!0}}),c(".ui-widget-header",g).css({background:b.bufferFullColor}),g.css({display:"block"}),h.css({display:"block"}),e.css({display:"block"}));T(a,a.origID)&&a.videoIsFullScreen&&(g.css({display:"none"}),h.css({display:"none"}),e.css({display:"none"}));Q(a,a.origID)&&(a.youTubeInterval=setInterval(function(){var e=!0;-1==r.indexOf("ipad")&&-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")||
a.youtubeWasStarted==YT.PlayerState.PLAYING||(e=!1);0!=a.isYouTubeReady&&(!b.isSeekBarInitialized&&0<a.player.getDuration()&&e&&(h.slider({value:0,step:.5,orientation:"horizontal",range:"min",max:a.player.getDuration(),slide:function(){a.is_seeking=!0;c("iframe",f).css({"pointer-events":"none"})},stop:function(b,e){a.is_seeking=!1;c("iframe",f).css({"pointer-events":"auto"});a.player.seekTo(e.value)},create:function(a,c){b.isSeekBarInitialized=!0}}),c(".ui-slider-range",h).css({background:b.seekbarColor})),
n.html(S(a.player.getDuration())+"/"+S(a.player.getCurrentTime())),a.is_buffer_complete||(a.bufferedTime=100*a.player.getVideoLoadedFraction(),g.progressbar({value:a.bufferedTime})),!a.is_seeking&&b.isSeekBarInitialized&&h.slider("value",a.player.getCurrentTime()))},500));T(a,a.origID)&&(a.vimeoInterval=setInterval(function(){n.html(S(a.totalTime)+"/"+S(a.curTime));0<a.totalTime||a.vimeo_player.api("getDuration",function(b){a.totalTime=b});a.vimeo_player.api("getCurrentTime",function(b){a.curTime=
b;0<b&&a.curTime++})},500));if(ea(a,a.origID)){var k=parseInt(g.width(),10);a.selfHostedInterval=setInterval(function(){a.curTime=document.getElementById(a.html5_video_id).currentTime;a.totalTime=document.getElementById(a.html5_video_id).duration;!b.isSeekBarInitialized&&0<a.totalTime&&(h.slider({value:0,step:.5,orientation:"horizontal",range:"min",max:a.totalTime,slide:function(){a.is_seeking=!0},stop:function(b,c){a.is_seeking=!1;document.getElementById(a.html5_video_id).currentTime=c.value},create:function(a,
c){b.isSeekBarInitialized=!0}}),c(".ui-slider-range",h).css({background:b.seekbarColor}));n.html(S(a.totalTime)+"/"+S(a.curTime));a.bufferedTime=document.getElementById(a.html5_video_id).buffered;a.is_buffer_complete||(a.bufferedTime=a.bufferedTime.length?parseFloat(document.getElementById(a.html5_video_id).buffered.end(0)):document.getElementById(a.html5_video_id).buffered,0<a.bufferedTime&&g.progressbar({value:a.bufferedTime*k/a.totalTime}));!a.is_seeking&&b.isSeekBarInitialized&&h.slider("value",
a.curTime)},500)}}function da(a,b,f,g,h,e,n){e=0;var l=c(".showHidePlaylistBut",f).width()+a.buttonsDistance,p=n,k="none";"none"==n&&(k="block");Q(a,a.origID)&&(p="none");c(".firstset_controls",f).css("display",n);g.css("display",n);h.css("display",n);"block"==n&&(e=a.showPlaylistButOrigLeft,l=a.fullscreenButOrigLeft);c(".largePlayButton",f).css({display:p});c(".fullscreenVimeoButton",f).css({display:k});b.showPlaylistBut&&c(".showHidePlaylistBut",f).css({left:e+"px"});b.showFullscreenBut&&c(".fullscreenBut",
f).css({left:l+"px",display:n})}function ta(a,b,f,g){Q(a,a.previousOrigID)&&(a.player.stopVideo(),c(".lbg_player",f).css({"z-index":-1}));T(a,a.previousOrigID)&&(a.vimeo_player.api("pause"),c(".lbg_vimeo_player",f).css({"z-index":-1}),a.vimeo_player.api("getVolume",function(a){b.initialVolume=a}));ea(a,a.previousOrigID)&&(document.getElementById(a.html5_video_id).pause(),c("#"+a.html5_video_id).css({"z-index":-1,width:0,height:0}))}function ra(a,b){a=String(a);var c="";if(a.length>b){a=a.substring(0,
b);var g=a.split(" ");var h=a.substring(b-2,b-1);""!=h&&(g.pop(),c="...");a=g.join(" ")}return a+c}function sa(a,b,f,g,h){f.css("top","0px");var e=0;b.isPlaylistSliderInitialized&&a.universal_video_player_sliderVertical.slider("destroy");b.isPlaylistSliderInitialized=!1;a.selectedCateg_total_images>b.numberOfThumbsPerScreen&&(a.universal_video_player_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(c,e){ca(e.value,f,b,a)}}),b.isPlaylistSliderInitialized=
!0,0>=b.borderWidth&&(e=a.universal_video_player_sliderVertical.width()/2),a.universal_video_player_sliderVertical.height(h.height()-15),a.universal_video_player_sliderVertical.css({display:"block",left:Math.floor(b.width-2*b.borderWidth+(b.borderWidth-a.universal_video_player_sliderVertical.width())/2)-e+"px"}),c(".ui-slider-handle",a.universal_video_player_sliderVertical).css({"background-color":b.playlistScrollerBgColorOFF}),c(".ui-slider-handle",a.universal_video_player_sliderVertical).mouseover(function(){c(this).css({"background-color":b.playlistScrollerBgColorON})}),
c(".ui-slider-handle",a.universal_video_player_sliderVertical).mouseout(function(){c(this).css({"background-color":b.playlistScrollerBgColorOFF})}),g.mousewheel(function(c,e,g,h){c.preventDefault();c=a.universal_video_player_sliderVertical.slider("value");if(1<parseInt(c,10)&&-1==parseInt(e,10)||100>parseInt(c,10)&&1==parseInt(e,10))c+=e,a.universal_video_player_sliderVertical.slider("value",c),ca(c,f,b,a)}))}function ua(a,b,f,g,h,e,n,l,p,k,m,q,A,u,x,v,r,w,D,G,t,J,K,N,M,L,F,H,C){g.stop(!0,!0);a.isCarouselScrolling=
!1;g.stop().animate({left:-1*e.width()+"px"},600,"easeOutQuad",function(){g.html("");for(var z=0;z<a.category_arr.length;z++)a.thumbsHolder_Thumb=c('<div class="thumbsHolder_ThumbOFF categUnit" rel="'+z+'"><div class="padding"><span class="title">'+a.category_arr[z]+"</span></div></div>"),g.append(a.thumbsHolder_Thumb),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_Thumb.height()+1)*z+"px",background:b.categoryRecordBgOffColor,"border-bottom-color":b.categoryRecordBottomBorderOffColor,color:b.categoryRecordTextOffColor}),
a.category_arr[z]==a.selectedCateg&&(a.current_img_no=z,a.thumbsHolder_Thumb.css({background:b.categoryRecordBgOnColor,"border-bottom-color":b.categoryRecordBottomBorderOnColor,color:b.categoryRecordTextOnColor}));a.thumbMarginTop=0;b.numberOfThumbsPerScreen=Math.floor((b.height-2*b.borderWidth)/(a.thumbsHolder_Thumb.height()+1))-1;a.selectedCateg_total_images=a.numberOfCategories;a.categsAreListed=!0;a.thumbsHolder_Thumbs=c(".thumbsHolder_ThumbOFF",f);sa(a,b,g,e,h);a.thumbsHolder_Thumbs.click(function(){var B=
c(this).attr("rel");a.selectedCateg=a.category_arr[B];ver_ie=fa();l.html(a.selectedCateg);ha(a,b,f,g,h,e,n,p,k,m,q,A,u,x,v,r,w,D,G,t,J,K,N,M,L,F,H,C,ver_ie)});a.thumbsHolder_Thumbs.mouseover(function(){c(this).css({background:b.categoryRecordBgOnColor,"border-bottom-color":b.categoryRecordBottomBorderOnColor,color:b.categoryRecordTextOnColor})});a.thumbsHolder_Thumbs.mouseout(function(){var e=c(this),f=e.attr("rel");a.current_img_no!=f&&e.css({background:b.categoryRecordBgOffColor,"border-bottom-color":b.categoryRecordBottomBorderOffColor,
color:b.categoryRecordTextOffColor})});g.stop().animate({left:"0px"},400,"easeOutQuad",function(){})})}function ha(a,b,f,g,h,e,n,l,p,k,m,q,A,u,x,v,E,w,D,G,t,J,K,N,M,L,F,H,C){g.stop(!0,!0);a.isCarouselScrolling=!1;a.categsAreListed=!1;m=k="";var z=!1;l=500;a.is_very_first&&(l=1);""!=a.search_val&&(l=1);g.css({left:-1*e.width()+"px"});g.html("");for(var B=a.selectedCateg_total_images=0;B<a.playlist_arr.length;B++){z=!1;if(""!=a.search_val){if(k=a.playlist_arr[B].title.toLowerCase(),m=a.playlist_arr[B].desc.toLowerCase(),
-1!=k.indexOf(a.search_val)||-1!=m.indexOf(a.search_val))z=!0}else-1!=a.playlist_arr[B].category.indexOf(a.selectedCateg+";")&&(z=!0);z&&(a.selectedCateg_total_images++,k=a.playlist_arr[B]["bottom-thumb"],thumbUnit="",b.playlistRecordShowImg&&(thumbUnit='<img src="'+k+'">'),a.thumbsHolder_Thumb=c('<div class="thumbsHolder_ThumbOFF" rel="'+(a.selectedCateg_total_images-1)+'" data-origID="'+B+'"><div class="padding">'+thumbUnit+'<span class="title">'+ra(a.playlist_arr[B].title,b.playlistRecordTitleLimit)+
'</span><span class="reg">'+ra(a.playlist_arr[B].desc,b.playlistRecordDescLimit)+"</span></div></div>"),g.append(a.thumbsHolder_Thumb),W(b,a,a.thumbsHolder_Thumb),a.thumbsHolder_Thumb.css({height:b.playlistRecordHeight+"px"}),c(".padding",a.thumbsHolder_Thumb).css({padding:b.playlistRecordPadding+"px"}),0==b.origThumbW&&(0==b.numberOfThumbsPerScreen&&(b.numberOfThumbsPerScreen=Math.floor((b.origHeight-2*b.borderWidth)/a.thumbsHolder_Thumb.height())),b.origNumberOfThumbsPerScreen=b.numberOfThumbsPerScreen,
b.origThumbW=a.thumbsHolder_Thumb.width(),b.origThumbH=a.thumbsHolder_Thumb.height(),p=c(".thumbsHolder_ThumbOFF .padding",f),b.origthumbLeftPadding=p.css("padding-left").substr(0,p.css("padding-left").lastIndexOf("px")),b.origthumbRightPadding=p.css("padding-right").substr(0,p.css("padding-left").lastIndexOf("px")),b.origthumbTopPadding=p.css("padding-top").substr(0,p.css("padding-left").lastIndexOf("px")),b.origthumbBottomPadding=p.css("padding-bottom").substr(0,p.css("padding-left").lastIndexOf("px")),
a.thumbMarginTop=Math.floor((h.height()-a.thumbsHolder_Thumb.height()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1)),a.origThumbMarginTop=a.thumbMarginTop,k=c(".thumbsHolder_ThumbOFF .title",f),m=c(".thumbsHolder_ThumbOFF .reg",f),k.css({"font-size":b.playlistTitleFontSize+"px","line-height":b.playlistTitleLineHeight+"px"}),m.css({"font-size":b.playlistDescFontSize+"px","line-height":b.playlistDescLineHeight+"px"}),-1!=k.css("font-size").lastIndexOf("px")?b.origthumbTitleFont=k.css("font-size").substr(0,
k.css("font-size").lastIndexOf("px")):-1!=k.css("font-size").lastIndexOf("em")&&(b.origthumbTitleFont=k.css("font-size").substr(0,k.css("font-size").lastIndexOf("em"))),-1!=k.css("line-height").lastIndexOf("px")?b.origthumbTitleLineHeight=k.css("line-height").substr(0,k.css("line-height").lastIndexOf("px")):-1!=k.css("line-height").lastIndexOf("em")&&(b.origthumbTitleLineHeight=k.css("line-height").substr(0,k.css("line-height").lastIndexOf("em"))),-1!=m.css("font-size").lastIndexOf("px")?b.origthumbRegFont=
m.css("font-size").substr(0,m.css("font-size").lastIndexOf("px")):-1!=m.css("font-size").lastIndexOf("em")&&(b.origthumbRegFont=m.css("font-size").substr(0,m.css("font-size").lastIndexOf("em"))),-1!=m.css("line-height").lastIndexOf("px")?b.origthumbRegLineHeight=m.css("line-height").substr(0,m.css("line-height").lastIndexOf("px")):-1!=m.css("line-height").lastIndexOf("em")&&(b.origthumbRegLineHeight=m.css("line-height").substr(0,m.css("line-height").lastIndexOf("em")))))}0!=b.origNumberOfThumbsPerScreen&&
(b.numberOfThumbsPerScreen=b.origNumberOfThumbsPerScreen,a.thumbMarginTop=a.origThumbMarginTop);sa(a,b,g,e,h);a.thumbsHolder_Thumbs=c(".thumbsHolder_ThumbOFF",f);a.thumbsHolder_Thumbs.removeClass("categUnit");k=c(".thumbsHolder_ThumbOFF .title",f);m=c(".thumbsHolder_ThumbOFF .reg",f);a.thumbsHolder_Thumbs.click(function(){var e=c(this).attr("rel");W(b,a,c(a.thumbsHolder_Thumbs[a.current_img_no]));a.thumbsClicked=!0;a.current_img_no=e-1;ba(1,a,b,f,g,q,A,u,x,v,E,w,D,G,t)});a.thumbsHolder_Thumbs.mouseenter(function(){var e=
c(this);e.attr("rel");X(b,a,e)});a.thumbsHolder_Thumbs.mouseleave(function(){var e=c(this),d=e.attr("rel");a.current_img_no!=d&&W(b,a,e)});qa(a,b,f,g,e,h,p,k,m,n);a.current_img_no=b.firstVideo;b.firstVideo>a.selectedCateg_total_images&&(a.current_img_no=a.selectedCateg_total_images);0>b.firstVideo&&(a.current_img_no=0);b.shuffle&&(a.current_img_no=Math.floor(Math.random()*a.selectedCateg_total_images));X(b,a,c(a.thumbsHolder_Thumbs[a.current_img_no]));a.origID=c("div[rel='"+a.current_img_no+"']").attr("data-origID");
q.html(a.playlist_arr[a.origID].title);a.currentImg=a.playlist_arr[a.origID];g.stop().animate({left:"0px"},l,"easeOutQuad",function(){b.shuffle&&ca(0,g,b,a)});if(a.is_very_first){if(a.haveYouTube){var R=function(c){a.youtubeWasStarted!=YT.PlayerState.PLAYING&&(a.youtubeWasStarted=c.data);c.data==YT.PlayerState.ENDED&&ba(1,a,b,f,g,q,A,u,x,v,E,w,D,G,t);c.data==YT.PlayerState.PAUSED&&v.removeClass("pauseBut");c.data==YT.PlayerState.PLAYING&&v.addClass("pauseBut")},O=function(c){-1==r.indexOf("ipad")&&
-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&(a.player.setVolume(100*b.initialVolume),b.autoPlayFirstVideo?void 0!=a.currentImg.youtube&&""!=a.currentImg.youtube&&(c.target.playVideo(),v.hasClass("pauseBut")||v.addClass("pauseBut")):(c.target.pauseVideo(),a.player.cueVideoById(a.currentImg.youtube)));a.isYouTubeReady=!0};h=document.createElement("script");h.src=b.youtubeJsUrl;e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(h,
e);window.onYouTubeIframeAPIReady=function(){void 0!=a.currentImg.youtube&&""!=a.currentImg.youtube?(a.player=new YT.Player(J,{width:a.new_width,height:b.height-2*b.borderWidth,videoId:a.currentImg.youtube,playerVars:{rel:0,wmode:"opaque",controls:0,showinfo:0,html5:1,modestbranding:1,cc_load_policy:0,iv_load_policy:3,fs:0,disablekb:1},events:{onReady:O,onStateChange:R}}),c(".lbg_player",f).css({"z-index":4})):a.player=new YT.Player(J,{width:"100%",height:"100%",videoId:"xoORbLlFsis",playerVars:{rel:0,
wmode:"opaque",controls:0,showinfo:0,html5:1,modestbranding:1,cc_load_policy:0,iv_load_policy:3,fs:0,disablekb:1},events:{onReady:O,onStateChange:R}})}}if(a.haveVimeo){var Q=function(c){ba(1,a,b,f,g,q,A,u,x,v,E,w,D,G,t)};void 0!=a.currentImg.vimeo&&""!=a.currentImg.vimeo?(c(".lbg_vimeo_player",f).html('<iframe id="'+t+'" src="//player.vimeo.com/video/'+a.currentImg.vimeo+"?api=1&amp;player_id="+t+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'),
c(".lbg_vimeo_player",f).css({"z-index":4})):c(".lbg_vimeo_player",f).html('<iframe id="'+t+'" src="//player.vimeo.com/video/?api=1&amp;player_id='+t+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');a.vimeo_iframe=c("#"+t)[0];a.vimeo_player=$f(a.vimeo_iframe);a.vimeo_player.addEvent("ready",function(){a.vimeo_player.api("setVolume",b.initialVolume);c(".lbg_vimeo_player",f).css({"z-index":4});b.autoPlayFirstVideo?void 0!=a.currentImg.vimeo&&
""!=a.currentImg.vimeo&&-1==r.indexOf("ipad")&&-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&a.vimeo_player.api("play"):a.vimeo_player.api("pause");a.vimeo_player.addEvent("finish",Q)})}a.haveSelfHosted&&(h="",b.autoPlayFirstVideo&&(h=' autoplay="autoplay"'),h=c('<video id="'+a.html5_video_id+'" width="100%" height="100%" preload="auto"'+h+"></video>"),f.append(h),c("#"+a.html5_video_id).css({"z-index":-1,width:0,height:0,top:0,
left:0,position:"absolute",background:"#000000"}),document.getElementById(a.html5_video_id).volume=b.initialVolume,void 0!=a.currentImg.selfhostedMP4&&""!=a.currentImg.selfhostedMP4&&(document.getElementById(a.html5_video_id).src=oa(C,a,a.html5_video_id),document.getElementById(a.html5_video_id).load(),c("#"+a.html5_video_id).css({"z-index":4,width:"100%",height:"100%"}),b.autoPlayFirstVideo&&(document.getElementById(a.html5_video_id).play(),-1==r.indexOf("ipad")&&-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&
-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&(v.hasClass("pauseBut")||v.addClass("pauseBut")))),document.getElementById(a.html5_video_id).addEventListener("ended",function(c){ba(1,a,b,f,g,q,A,u,x,v,E,w,D,G,t)},!1));b.googleTrakingOn&&(ga("create",b.googleTrakingCode,"auto"),h=C="",void 0!=a.currentImg.youtube&&""!=a.currentImg.youtube&&(C=a.currentImg.youtube,h=a.googleYouTubeCateg),void 0!=a.currentImg.vimeo&&""!=a.currentImg.vimeo&&(C=a.currentImg.vimeo,h=a.googleVimeoCateg),
void 0!=a.currentImg.selfhostedMP4&&""!=a.currentImg.selfhostedMP4&&(C=a.currentImg.selfhostedMP4,h=a.googleSelfHostedCateg),ga("send","event",h,"Play","Title: "+a.currentImg.title+"  ---  ID: "+C));pa(a,b,f,A,u,w,x,E,t);w.css({left:0,height:b.borderWidth+"px",bottom:-1*b.borderWidth+"px"});U(a,b,f,K,v,N,M,L,F,H,D,G,!0,!0);void 0!=a.currentImg.vimeo&&""!=a.currentImg.vimeo&&da(a,b,f,A,u,w,"none")}a.is_very_first&&(a.is_very_first=!1,a.previousOrigID=a.origID)}function U(a,b,c,g,h,e,n,l,p,k,m,q,r,
u){a.totalButtonsDistance=0;b.showRewindBut?(g.css({left:0,bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):g.css({display:"none",width:0,height:0,padding:0,margin:0});b.showPlayBut?(h.css({left:g.width()+a.totalButtonsDistance+"px",bottom:"0px","background-color":b.playButColorOff}),a.totalButtonsDistance+=a.buttonsDistance):h.css({display:"none",width:0,height:0,padding:0,margin:0});b.showVolumeBut?(e.css({left:g.width()+h.width()+a.totalButtonsDistance+"px",bottom:"0px"}),a.totalButtonsDistance+=
a.buttonsDistance):e.css({display:"none",width:0,height:0,padding:0,margin:0});b.showFacebookBut?(n.css({left:g.width()+h.width()+e.width()+a.totalButtonsDistance+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):n.css({display:"none",width:0,height:0,padding:0,margin:0});b.showTwitterBut?(l.css({left:g.width()+h.width()+e.width()+n.width()+a.totalButtonsDistance+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):l.css({display:"none",width:0,height:0,padding:0,margin:0});
b.showInfoBut&&u?(p.css({display:"block",width:a.origInfoWidth+"px",height:a.origInfoHeight+"px",left:g.width()+h.width()+e.width()+n.width()+l.width()+a.totalButtonsDistance+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):p.css({display:"none",width:0,height:0,padding:0,margin:0});b.showDownloadBut&&r?(k.css({display:"block",width:a.origDownloadWidth+"px",height:a.origDownloadHeight+"px",left:g.width()+h.width()+e.width()+n.width()+l.width()+p.width()+a.totalButtonsDistance+"px",bottom:"0px"}),
a.totalButtonsDistance+=a.buttonsDistance):k.css({display:"none",width:0,height:0,padding:0,margin:0});b.showPlaylistBut?(a.showPlaylistButOrigLeft=g.width()+h.width()+e.width()+n.width()+l.width()+p.width()+k.width()+a.totalButtonsDistance,m.css({left:a.showPlaylistButOrigLeft+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):m.css({display:"none",width:0,height:0,padding:0,margin:0});b.showFullscreenBut?(a.fullscreenButOrigLeft=g.width()+h.width()+e.width()+n.width()+l.width()+p.width()+
k.width()+m.width()+a.totalButtonsDistance,q.css({left:a.fullscreenButOrigLeft+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):q.css({display:"none",width:0,height:0,padding:0,margin:0})}function na(a,b,f,g,h,e,n,l,p,k,m,q,r,u,x){if(a.videoIsFullScreen){c("body").css("margin-top",a.origBodyTopMargin);c("body").css("margin-right",a.origBodyRightMargin);c("body").css("margin-bottom",a.origBodyBottomMargin);c("body").css("margin-left",a.origBodyLeftMargin);c("body").css("overflow",a.origBodyOverflow);
c("html").css("overflow",a.origHtmlOverflow);a.videoIsFullScreen=!1;f.css("position",a.containerOrigPosition);f.css("z-index",a.containerOrigZindex);e.css({display:"block"});T(a,a.origID)||(g.css({display:"block"}),h.css({display:"block"}));if(b.playlistVisible){a.new_width=parseInt(b.width-b.playlistWidth/(b.origWidth/b.width)-3*b.borderWidth,10);var v="block";b.showNextPrevBut&&(k.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px"}),m.css({right:-1*(b.borderWidth+b.playlistWidth/
(b.origWidth/b.width)-k.width()-a.buttonsDistanceSeekBar)+"px"}));b.showShuffleBut&&q.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width)-k.width()-m.width()-a.totalButtonsDistanceSeekBar)+"px"})}else a.new_width=parseInt(b.width-2*b.borderWidth,10),v="none",b.showNextPrevBut&&(k.css({right:0}),m.css({right:k.width()+a.buttonsDistanceSeekBar+"px"})),b.showShuffleBut&&q.css({right:k.width()+m.width()+a.totalButtonsDistanceSeekBar+"px"});a.new_height=parseInt(b.height-2*b.borderWidth,
10);n.css({display:v});b.showCategs&&l.css({display:v});b.showSearch&&(p.css({display:v}),b.width<=a.minimalWidthSearch&&p.css({display:"none"}));b.isPlaylistSliderInitialized&&b.playlistVisible&&a.universal_video_player_sliderVertical.css({visibility:"visible"});b.showInfoBut&&r.css({bottom:0});b.showPlaylistBut&&(u.css({display:"block"}),x.css({left:parseInt(x.css("left").substr(0,x.css("left").lastIndexOf("px")),10)+u.width()+a.buttonsDistance+"px"}));f.width(a.new_width);f.height(a.new_height);
f.css({left:b.borderWidth+"px",top:b.borderWidth+"px"});e.css({left:0,bottom:-1*b.borderWidth+"px",background:"none"});g.css({bottom:0});h.css({bottom:0})}else c("body").css("margin",0),c("body").css("overflow","hidden"),c("html").css("overflow","hidden"),f.css("position","fixed"),f.css("z-index",999990),a.new_width=window.innerWidth,a.new_height=window.innerHeight,a.videoIsFullScreen=!0,T(a,a.origID)&&(g.css({display:"none"}),h.css({display:"none"}),e.css({display:"none"})),n.css({display:"none"}),
b.showCategs&&l.css({display:"none"}),b.showSearch&&p.css({display:"none"}),b.isPlaylistSliderInitialized&&a.universal_video_player_sliderVertical.css({visibility:"hidden"}),b.showNextPrevBut&&(k.css({right:0}),m.css({right:k.width()+a.buttonsDistanceSeekBar+"px"})),b.showShuffleBut&&q.css({right:k.width()+m.width()+a.totalButtonsDistanceSeekBar+"px"}),b.showInfoBut&&r.css({bottom:b.borderWidth+"px"}),b.showPlaylistBut&&(u.css({display:"none"}),x.css({left:parseInt(x.css("left").substr(0,x.css("left").lastIndexOf("px")),
10)-u.width()-a.buttonsDistance+"px"})),f.width(a.new_width),f.height(a.new_height),f.css({top:"0px",left:"0px"}),e.css({left:0,bottom:"1px",background:b.controlsBgFullScreenColor}),g.css({bottom:b.borderWidth+"px"}),h.css({bottom:b.borderWidth+"px"});a.haveYouTube&&c(".lbg_player",f).css({width:a.new_width+"px",height:a.new_height+"px"});a.haveVimeo&&c(".lbg_vimeo_player",f).css({width:a.new_width+"px",height:a.new_height+"px"});ka(a,f,n,a.new_width)}function ja(a,b,c){c.html('<div class="movieTitle">'+
a.playlist_arr[a.origID].title+'</div><div class="movieDesc">'+a.playlist_arr[a.origID].desc+"</div>")}var r=navigator.userAgent.toLowerCase(),ma=function(a){return document.getElementById(a).canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')};c.fn.universal_video_player=function(a){a=c.extend({},c.fn.universal_video_player.defaults,a);return this.each(function(){var b=c(this);responsiveWidth=b.parent().width();responsiveHeight=b.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=
c(window).width(),responsiveHeight=c(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));a.width=parseInt(a.width,10);a.height=parseInt(a.height,10);b.css("display","block");var f=c("<div></div>").addClass("universal_video_playerBorder"),
g=c("<div></div>").addClass("universal_video_player").addClass(a.skin),h=c('<div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>  <div class="slider-vertical"></div>      <div class="selectedCategDiv"><div class="innerSelectedCategDiv">READING CATEGORIES...</div></div>     <div class="searchDiv"><input class="search_term" type="text" value="search..." /></div>  <div class="top_title">Movie Title</div>  <div class="the_timer">00:00/00:00</div>  <div class="videoBuffer"></div> <div class="videoSeek"></div>                <div class="all_controls">             <div class="firstset_controls">                          <div class="rewindBut" title="Rewind"></div><div class="playBut" title="Play/Pause"></div> <div class="volumeAll"><div class="volumeSlider"></div><div class="volumeBut" title="Mute/Unmute"></div></div> <div class="facebookBut" title="Facebook"></div><div class="twitterBut" title="Twitter"></div><div class="infoBut"  title="Info"></div><div class="downloadBut" title="Download File"></div>          </div>           <div class="showHidePlaylistBut" title="Show/Hide Playlist"></div><div class="fullscreenBut" title="FullScreen"></div>  <div class="shuffleBut" title="Shuffle"></div><div class="prevBut" title="Previous"></div><div class="nextBut" title="Next"></div>              </div>             <div class="videoInfoBox"></div>');
b.wrap(g);b.after(h);var e=b.parent(".universal_video_player");e.wrap(f);var n=e.parent(".universal_video_playerBorder"),l=c(".selectedCategDiv",e),p=c(".innerSelectedCategDiv",e),k=c(".searchDiv",e),m=c(".search_term",e),q=c(".nextBut",e),A=c(".prevBut",e),u=c(".shuffleBut",e),x=c(".top_title",e),v=c(".the_timer",e),E=c(".all_controls",e),w=c(".videoBuffer",e),D=c(".videoSeek",e),G=c(".rewindBut",e),t=c(".playBut",e),J=c(".volumeAll",e),K=c(".volumeBut",e),N=c(".volumeSlider",e),M=c(".facebookBut",
e),L=c(".twitterBut",e),F=c(".infoBut",e),H=c(".downloadBut",e),C=c(".showHidePlaylistBut",e),z=c(".fullscreenBut",e),B=c(".videoInfoBox",e);f=Math.floor(1E5*Math.random());g=c("<div></div>").addClass("lbg_player");b.append(g);var R="lbg_player"+f;c(".lbg_player",e).attr("id",R);g=c("<div></div>").addClass("lbg_vimeo_player");b.append(g);var O="lbg_vimeo_player"+f,S=fa(),W=a.defaultEffect,d={current_img_no:0,currentImg:0,current_imgInside:"",windowWidth:0,carouselStep:0,thumbMarginTop:0,origThumbMarginTop:0,
thumbsClicked:!1,haveYouTube:!1,haveVimeo:!1,haveSelfHosted:!1,html5_video_id:"html5_video_id_"+f,playerRatio:a.origWidth/a.origHeight,total_images:0,playlist_arr:"",category_arr:"",selectedCateg:"",categsAreListed:!1,numberOfCategories:0,universal_video_player_sliderVertical:"",search_val:"",is_very_first:!0,is_very_first_vimeo:!0,thumbsHolder_Thumb:"",thumbsHolder_Thumbs:"",containerOrigPosition:"",containerOrigZindex:"",youTubeInterval:"",selfHostedInterval:"",vimeoInterval:"",bufferedTime:0,is_buffer_complete:!1,
is_seeking:!1,totalTime:0,curTime:0,new_width:0,new_height:0,buttonsDistance:15,totalButtonsDistance:0,showPlaylistButOrigLeft:0,fullscreenButOrigLeft:0,origInfoWidth:0,origInfoHeight:0,origDownloadWidth:0,origDownloadHeight:0,buttonsDistanceSeekBar:7,totalButtonsDistanceSeekBar:0,minimalWidthSearch:445,minimalWidthDownload:370,minimalWidthInfo:340,showHidePlaylistMiliseconds:0,googleYouTubeCateg:"YouTube Videos",googleVimeoCateg:"Vimeo Videos",googleSelfHostedCateg:"Self-Hosted Videos",ajaxReturnedImagesNo:0,
totalImagesNo:0,videoIsFullScreen:!1,youtubeWasStarted:-1,origBodyTopMargin:0,origBodyRightMargin:0,origBodyBottomMargin:0,origBodyLeftMargin:0,origBodyOverflow:"",origHtmlOverflow:"",origID:0,previousOrigID:0,player:!1,isYouTubeReady:!1,vimeo_player:!1,vimeo_iframe:!1};d.origInfoWidth=F.width();d.origInfoHeight=F.height();d.origDownloadWidth=H.width();d.origDownloadHeight=H.height();d.containerOrigPosition=e.css("position");d.containerOrigZindex=e.css("z-index");d.origBodyTopMargin=c("body").css("margin-top");
d.origBodyRightMargin=c("body").css("margin-right");d.origBodyBottomMargin=c("body").css("margin-bottom");d.origBodyLeftMargin=c("body").css("margin-left");d.origBodyOverflow=c("body").css("overflow");d.origHtmlOverflow=c("html").css("overflow");var I=c(".thumbsHolderWrapper",e),V=c(".thumbsHolderVisibleWrapper",e),P=c(".thumbsHolder",e);d.universal_video_player_sliderVertical=c(".slider-vertical",e);I.css({background:a.playlistBgColor});a.showTopTitle?x.css({color:a.topTitleColor,top:-1*a.borderWidth+
(a.borderWidth-x.height())/2+"px"}):x.css({display:"none"});a.showTimer?v.css({color:a.timerColor,top:-1*a.borderWidth+(a.borderWidth-v.height())/2+"px"}):v.css({display:"none"});n.width(a.width);n.height(a.height);n.css("background",a.borderColor);d.new_width=parseInt(a.width-a.playlistWidth/(a.origWidth/a.width)-3*a.borderWidth,10);e.width(d.new_width);e.height(a.height-2*a.borderWidth);e.css({left:a.borderWidth+"px",top:a.borderWidth+"px"});c(".lbg_player",e).width(d.new_width);c(".lbg_player",
e).height(e.height());c(".lbg_vimeo_player",e).width(d.new_width);c(".lbg_vimeo_player",e).height(e.height());V.width(a.playlistWidth/(a.origWidth/a.width));V.height(e.height());I.width(a.playlistWidth/(a.origWidth/a.width));I.height(e.height());I.css({top:0,right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px"});P.width(a.playlistWidth/(a.origWidth/a.width));P.css("top","0px");l.css({width:a.playlistWidth/(a.origWidth/a.width)+"px","background-color":a.selectedCategBg,"background-position":"2px 50%",
top:"-20px",right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px"});p.css({color:a.selectedCategOffColor,"background-position":a.playlistWidth/(a.origWidth/a.width)-9+"px 50%"});var y=b.find("ul:first").children();d.playlist_arr=[];d.category_arr=[];var U=[];y.each(function(){d.currentImg=c(this);d.currentImg.is("li")||(d.currentImg=d.currentImg.find("li:first"));if(d.currentImg.is("li")){d.currentImg.css("display","none");d.total_images++;d.playlist_arr[d.total_images-1]=[];d.playlist_arr[d.total_images-
1].title="";d.playlist_arr[d.total_images-1].desc="";d.playlist_arr[d.total_images-1]["bottom-thumb"]="";d.playlist_arr[d.total_images-1].category="";d.playlist_arr[d.total_images-1].youtube="";d.playlist_arr[d.total_images-1].vimeo="";d.playlist_arr[d.total_images-1].selfhostedMP4="";d.playlist_arr[d.total_images-1].selfhostedWEBM="";void 0!=c(y[d.total_images-1]).attr("data-title")&&""!=c(y[d.total_images-1]).attr("data-title")&&(d.playlist_arr[d.total_images-1].title=c(y[d.total_images-1]).attr("data-title"));
void 0!=c(y[d.total_images-1]).attr("data-desc")&&""!=c(y[d.total_images-1]).attr("data-desc")&&(d.playlist_arr[d.total_images-1].desc=c(y[d.total_images-1]).attr("data-desc"));void 0!=c(y[d.total_images-1]).attr("data-bottom-thumb")&&""!=c(y[d.total_images-1]).attr("data-bottom-thumb")&&(d.playlist_arr[d.total_images-1]["bottom-thumb"]=c(y[d.total_images-1]).attr("data-bottom-thumb"));void 0!=c(y[d.total_images-1]).attr("data-youtube")&&""!=c(y[d.total_images-1]).attr("data-youtube")&&(d.playlist_arr[d.total_images-
1].youtube=c(y[d.total_images-1]).attr("data-youtube"));void 0!=c(y[d.total_images-1]).attr("data-vimeo")&&""!=c(y[d.total_images-1]).attr("data-vimeo")&&(d.playlist_arr[d.total_images-1].vimeo=c(y[d.total_images-1]).attr("data-vimeo"));void 0!=c(y[d.total_images-1]).attr("data-selfhostedMP4")&&""!=c(y[d.total_images-1]).attr("data-selfhostedMP4")&&(d.playlist_arr[d.total_images-1].selfhostedMP4=c(y[d.total_images-1]).attr("data-selfhostedMP4"));void 0!=c(y[d.total_images-1]).attr("data-selfhostedWEBM")&&
""!=c(y[d.total_images-1]).attr("data-selfhostedWEBM")&&(d.playlist_arr[d.total_images-1].selfhostedWEBM=c(y[d.total_images-1]).attr("data-selfhostedWEBM"));if(void 0!=c(y[d.total_images-1]).attr("data-category")&&""!=c(y[d.total_images-1]).attr("data-category")){d.playlist_arr[d.total_images-1].category=c(y[d.total_images-1]).attr("data-category")+";";U=c(y[d.total_images-1]).attr("data-category").split(";");for(var a=0;a<U.length;a++)-1===d.category_arr.indexOf(U[a])&&d.category_arr.push(U[a])}void 0!=
c(y[d.total_images-1]).attr("data-youtube")&&""!=c(y[d.total_images-1]).attr("data-youtube")&&(d.haveYouTube=!0);void 0!=c(y[d.total_images-1]).attr("data-vimeo")&&""!=c(y[d.total_images-1]).attr("data-vimeo")&&(d.haveVimeo=!0);void 0!=c(y[d.total_images-1]).attr("data-selfhostedMP4")&&""!=c(y[d.total_images-1]).attr("data-selfhostedMP4")&&(d.haveSelfHosted=!0)}});d.numberOfCategories=d.category_arr.length;d.category_arr.sort();d.selectedCateg=a.firstCateg;""==a.firstCateg&&-1===d.category_arr.indexOf(a.firstCateg)&&
(d.selectedCateg=d.category_arr[0]);p.html(d.selectedCateg);var Y=c(".thumbsHolder_ThumbOFF .padding",e);var Z=c(".thumbsHolder_ThumbOFF .title",e);var aa=c(".thumbsHolder_ThumbOFF .reg",e);for(d.totalImagesNo=0;d.totalImagesNo<d.playlist_arr.length;d.totalImagesNo++)""!=d.playlist_arr[d.totalImagesNo].youtube&&a.getYouTubeData?c.get(a.pathToAjaxFiles+"get_gdata.php",{cur_i:d.totalImagesNo,youtubeID:d.playlist_arr[d.totalImagesNo].youtube},function(b){d.ajaxReturnedImagesNo++;b=b.split("#----#");
the_i=parseInt(b[0],10);if(void 0==d.playlist_arr[the_i]["bottom-thumb"]||""==d.playlist_arr[the_i]["bottom-thumb"])d.playlist_arr[the_i]["bottom-thumb"]=b[1];if(void 0==d.playlist_arr[the_i].title||""==d.playlist_arr[the_i].title)d.playlist_arr[the_i].title=b[2];if(void 0==d.playlist_arr[the_i].desc||""==d.playlist_arr[the_i].desc)d.playlist_arr[the_i].desc=b[3];the_i==a.firstVideo&&ja(d,a,B);d.ajaxReturnedImagesNo==d.totalImagesNo&&ha(d,a,e,P,I,V,l,k,Y,Z,aa,x,w,D,v,t,B,E,C,z,O,R,G,J,M,L,F,H,S)}):
d.ajaxReturnedImagesNo++;a.getYouTubeData?d.haveYouTube||ha(d,a,e,P,I,V,l,k,Y,Z,aa,x,w,D,v,t,B,E,C,z,O,R,G,J,M,L,F,H,S):ha(d,a,e,P,I,V,l,k,Y,Z,aa,x,w,D,v,t,B,E,C,z,O,R,G,J,M,L,F,H,S);f=c("<div></div>").addClass("largePlayButton");e.append(f);c(".largePlayButton",e).click(function(){t.click()});Q(d,d.origID)&&c(".largePlayButton",e).css({display:"none"});f=c("<div></div>").addClass("fullscreenVimeoButton");e.append(f);c(".fullscreenVimeoButton",e).mouseover(function(){c(this).css({background:"url("+
a.absUrl+"skins/"+a.skin+"/fullscreenvimeo.png) no-repeat left bottom"})});c(".fullscreenVimeoButton",e).mouseout(function(){c(this).css({background:"none"})});f=c('<a href="'+a.logoLink+'" target="'+a.logoTarget+'"><img src="'+a.logoImagePath+'"></a>').addClass("yourLogo");e.append(f);a.showLogo||c(".yourLogo",e).css({display:"none"});a.showRewindBut&&G.click(function(){var a;ea(d,d.origID)&&(document.getElementById(d.html5_video_id).currentTime=0,document.getElementById(d.html5_video_id).play());
Q(d,d.origID)&&0!=d.isYouTubeReady&&(a=-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?d.youtubeWasStarted==YT.PlayerState.PLAYING?!0:!1:!0)&&(d.player.seekTo(0),d.player.playVideo())});a.showPlayBut&&(t.mouseover(function(){t.css({"background-color":a.playButColorOn})}),t.mouseout(function(){t.css({"background-color":a.playButColorOff})}),t.click(function(){var a;ea(d,d.origID)&&(t.hasClass("pauseBut")?(document.getElementById(d.html5_video_id).pause(),
t.removeClass("pauseBut")):(document.getElementById(d.html5_video_id).play(),t.addClass("pauseBut")));Q(d,d.origID)&&0!=d.isYouTubeReady&&(a=-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?d.youtubeWasStarted==YT.PlayerState.PLAYING?!0:!1:!0)&&(t.hasClass("pauseBut")?(d.player.pauseVideo(),t.removeClass("pauseBut")):(d.player.playVideo(),t.addClass("pauseBut")))}));a.showVolumeBut&&(N.slider({value:a.initialVolume,
orientation:"vertical",range:"max",max:1,step:.05,animate:!0,slide:function(b,f){c("iframe",e).css({"pointer-events":"none"});a.initialVolume=f.value;Q(d,d.origID)&&0!=d.isYouTubeReady&&(d.player.unMute(),K.removeClass("volumeButtonMute"),d.player.setVolume(100*a.initialVolume));ea(d,d.origID)&&(document.getElementById(d.html5_video_id).muted=!1,document.getElementById(d.html5_video_id).volume=a.initialVolume,K.removeClass("volumeButtonMute"))},stop:function(a,b){c("iframe",e).css({"pointer-events":"auto"})}}),
N.css({background:a.volumeOnColor}),N.css({"border-color":a.volumeOffColor}),c(".ui-slider-range",N).css({background:a.volumeOffColor}),J.mouseover(function(){N.css({display:"block"})}),J.mouseout(function(){N.css({display:"none"})}),K.click(function(){d.haveYouTube&&0!=d.isYouTubeReady&&(d.player.isMuted()?(K.removeClass("volumeButtonMute"),d.player.unMute(),d.player.setVolume(100*a.initialVolume)):(K.addClass("volumeButtonMute"),d.player.setVolume(0),d.player.mute()));d.haveSelfHosted&&(1==document.getElementById(d.html5_video_id).muted?
(document.getElementById(d.html5_video_id).muted=!1,document.getElementById(d.html5_video_id).volume=a.initialVolume,K.removeClass("volumeButtonMute")):(document.getElementById(d.html5_video_id).muted=!0,document.getElementById(d.html5_video_id).volume=0,K.addClass("volumeButtonMute")))}));a.showFacebookBut&&(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,version:"v2.8",status:!0,cookie:!0,xfbml:!0})},function(a,b,c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),
a.id=c,a.src="//connect.facebook.com/en_US/sdk.js",d.parentNode.insertBefore(a,d))}(document,"script","facebook-jssdk"),M.click(function(){FB.ui({method:"feed",name:a.facebookShareTitle,caption:d.playlist_arr[d.origID].title,description:a.facebookShareDescription,link:document.URL},function(a){})}));a.showTwitterBut&&L.click(function(){window.open("https://twitter.com/intent/tweet?url="+document.URL+"&text="+d.playlist_arr[d.origID].title,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")});
a.showInfoBut&&(F.click(function(){B.slideToggle(500,"easeOutCirc")}),ja(d,a,B));a.showDownloadBut&&H.click(function(){Q(d,d.origID)||T(d,d.origID)||window.open(a.pathToDownloadFile+"download.php?the_file="+d.playlist_arr[d.origID].selfhostedMP4)});C.click(function(){a.showPlaylistOnInit||I.css("visibility","visible");"none"!=I.css("display")?(a.playlistVisible=!1,d.new_width=parseInt(a.width-2*a.borderWidth,10),e.width(d.new_width),I.css({display:"none"}),a.showCategs&&l.css({display:"none"}),a.showSearch&&
k.css({display:"none"}),a.isPlaylistSliderInitialized&&d.universal_video_player_sliderVertical.css({visibility:"hidden"}),a.showNextPrevBut&&(q.css({right:0}),A.css({right:q.width()+d.buttonsDistanceSeekBar+"px"})),a.showShuffleBut&&u.css({right:q.width()+A.width()+d.totalButtonsDistanceSeekBar+"px"})):(d.showHidePlaylistMiliseconds=300,a.playlistVisible=!0,d.new_width=parseInt(a.width-a.playlistWidth/(a.origWidth/a.width)-3*a.borderWidth,10),e.width(d.new_width),I.css({display:"block"}),a.showCategs&&
l.css({display:"block"}),!a.showSearch||a.width<=d.minimalWidthSearch||k.css({display:"block"}),a.isPlaylistSliderInitialized&&d.universal_video_player_sliderVertical.css({visibility:"visible"}),a.showNextPrevBut&&(q.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px"}),A.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width)-q.width()-d.buttonsDistanceSeekBar)+"px"})),a.showShuffleBut&&u.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width)-q.width()-
A.width()-d.totalButtonsDistanceSeekBar)+"px"}));d.haveYouTube&&c(".lbg_player",e).animate({width:d.new_width+"px"},d.showHidePlaylistMiliseconds,"easeOutQuad",function(){});d.haveVimeo&&c(".lbg_vimeo_player",e).animate({width:d.new_width+"px"},d.showHidePlaylistMiliseconds,"easeOutQuad",function(){});ka(d,e,I,d.new_width)});a.showFullscreenBut&&(z.click(function(){screenfull.enabled&&-1==navigator.userAgent.indexOf("Android")?screenfull.toggle():na(d,a,e,w,D,E,I,l,k,q,A,u,B,C,z)}),d.totalButtonsDistance+=
d.buttonsDistance);c(".fullscreenVimeoButton",e).click(function(){screenfull.enabled&&-1==navigator.userAgent.indexOf("Android")?screenfull.toggle():na(d,a,e,w,D,E,I,l,k,q,A,u,B,C,z)});Q(d,d.origID)&&c(".fullscreenVimeoButton",e).css({display:"none"});screenfull.enabled&&-1==navigator.userAgent.indexOf("Android")&&document.addEventListener(screenfull.raw.fullscreenchange,function(){delayTime=50;11<=S&&(delayTime=200);setTimeout(function(){na(d,a,e,w,D,E,I,l,k,q,A,u,B,C,z)},delayTime)});d.totalButtonsDistanceSeekBar=
0;a.showNextPrevBut?(q.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px",bottom:"0px"}),q.click(function(){d.categsAreListed||ba(1,d,a,e,P,x,w,D,v,t,B,E,C,z,O)}),A.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width)-q.width()-d.buttonsDistanceSeekBar)+"px",bottom:"0px"}),A.click(function(){d.categsAreListed||ba(-1,d,a,e,P,x,w,D,v,t,B,E,C,z,O)}),d.totalButtonsDistanceSeekBar=3*d.buttonsDistanceSeekBar):(q.css({display:"none",width:0,height:0,padding:0,margin:0}),
A.css({display:"none",width:0,height:0,padding:0,margin:0}));a.showShuffleBut?(u.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width)-q.width()-A.width()-d.totalButtonsDistanceSeekBar)+"px",bottom:"0px"}),a.shuffle&&u.addClass("VideoShuffleON"),u.click(function(){a.shuffle?(u.removeClass("VideoShuffleON"),a.shuffle=!1):(u.addClass("VideoShuffleON"),a.shuffle=!0)})):u.css({display:"none",width:0,height:0,padding:0,margin:0});P.swipe({swipeStatus:function(b,c,e,f,g,h){"up"!=e&&"down"!=
e||0==f||(currentScrollVal=d.universal_video_player_sliderVertical.slider("value"),currentScrollVal="up"==e?currentScrollVal-1.5:currentScrollVal+1.5,d.universal_video_player_sliderVertical.slider("value",currentScrollVal),ca(currentScrollVal,P,a,d))},threshold:100,maxTimeThreshold:500,fingers:"all"});k.css({width:a.playlistWidth/(a.origWidth/a.width)+"px","background-color":a.searchAreaBg,top:3+(a.height-2*a.borderWidth)+"px",right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px"});
m.val(a.searchInputText);m.css({width:parseInt(a.playlistWidth/(a.origWidth/a.width),10)-100+"px","background-color":a.searchInputBg,"border-color":a.searchInputBorderColor,color:a.searchInputTextColor});void 0!=d.currentImg.vimeo&&""!=d.currentImg.vimeo&&da(d,a,e,w,D,E,"none");a.showSearch?(m.on("click",function(){c(this).val("")}),m.on("input",function(){d.search_val=m.val().toLowerCase();ha(d,a,e,P,I,V,l,k,Y,Z,aa,x,w,D,v,t,B,E,C,z,O,R,G,J,M,L,F,H,S)})):m.css({display:"none"});a.showCategs?(l.click(function(){d.search_val=
"";m.val(a.searchInputText);ua(d,a,e,P,I,V,l,p,k,Y,Z,aa,x,w,D,v,t,B,E,C,z,O,R,G,J,M,L,F,H)}),l.mouseover(function(){p.css({color:a.selectedCategOnColor})}),l.mouseout(function(){p.css({color:a.selectedCategOffColor})})):l.css({display:"none"});a.origWidth!=a.width&&la(d,a,W,b,h,e,n,P,V,I,Y,Z,aa,l,p,k,m,G,t,J,M,L,F,H,C,z,q,A,u,w,D,E,O);a.showPlaylistOnInit?d.showHidePlaylistMiliseconds=300:(d.showHidePlaylistMiliseconds=0,I.css("visibility","hidden"),setTimeout(function(){C.click()},100));0===a.initialVolume&&
setTimeout(function(){d.haveYouTube?0!=d.isYouTubeReady?K.click():setTimeout(function(){K.click()},2E3):K.click()},1500);var X=!1,ia=!0;c(window).resize(function(){var f=fa();ia=!0;-1!=f&&9==f&&0==d.windowWidth&&(ia=!1);d.windowWidth==c(window).width()?(ia=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,ia=!0)):d.windowWidth=c(window).width();a.responsive&&ia&&(!1!==X&&clearTimeout(X),X=setTimeout(function(){la(d,
a,W,b,h,e,n,P,V,I,Y,Z,aa,l,p,k,m,G,t,J,M,L,F,H,C,z,q,A,u,w,D,E,O)},300))})})};c.fn.myReverse=[].reverse;c.fn.universal_video_player.defaults={skin:"whiteControllers",width:980,height:399,width100Proc:!1,height100Proc:!1,shuffle:!1,firstVideo:0,initialVolume:1,loop:!0,showCategs:!0,showSearch:!0,showTopTitle:!0,showTimer:!0,showRewindBut:!0,showPlayBut:!0,showVolumeBut:!0,showFacebookBut:!0,facebookAppID:"1620027148224169",facebookShareTitle:"Universal Video Player",facebookShareDescription:"A top-notch responsive HTML5 Video Player compatible with all major browsers and mobile devices.",
showTwitterBut:!0,showInfoBut:!0,showDownloadBut:!0,showPlaylistBut:!0,showFullscreenBut:!0,showShuffleBut:!0,showNextPrevBut:!0,borderWidth:20,borderColor:"#4a4a4a",playlistWidth:282,absUrl:"",pathToDownloadFile:"",suggestedQuality:"default",controlsBgFullScreenColor:"#000000",playlistVisible:!0,playlistScrollerBgColorOFF:"#CCCCCC",playlistScrollerBgColorON:"#FFFFFF",responsive:!1,responsiveRelativeToBrowser:!0,numberOfThumbsPerScreen:0,origNumberOfThumbsPerScreen:0,logoImagePath:"skins/logo_watermark.png",
logoLink:"http://codecanyon.net/user/LambertGroup?ref=LambertGroup",logoTarget:"_blank",showLogo:!0,autoPlayFirstVideo:!0,playlistRecordShowImg:!0,playlistRecordShowTitle:!0,playlistRecordShowDesc:!0,playlistRecordHeight:89,playlistRecordPadding:10,playlistTitleFontSize:15,playlistTitleLineHeight:19,playlistDescFontSize:12,playlistDescLineHeight:15,playlistRecordBgOffColor:"#eeeeee",playlistRecordTitleOffColor:"#333333",playlistRecordDescOffColor:"#333333",playlistRecordBgOffImgOpacity:100,playlistRecordBgOnColor:"#de1a21",
playlistRecordTitleOnColor:"#FFFFFF",playlistRecordDescOnColor:"#FFFFFF",playlistRecordBgOnImgOpacity:100,playlistBgColor:"#4a4a4a",playlistRecordTitleLimit:22,playlistRecordDescLimit:84,getYouTubeData:!1,pathToAjaxFiles:"",showPlaylistOnInit:!0,categoryRecordBgOffColor:"#000000",categoryRecordBgOnColor:"#252525",categoryRecordBottomBorderOffColor:"#333333",categoryRecordBottomBorderOnColor:"#333333",categoryRecordTextOffColor:"#4c4c4c",categoryRecordTextOnColor:"#de1a21",firstCateg:"",selectedCategBg:"transparent",
selectedCategOffColor:"#FFFFFF",selectedCategOnColor:"#de1a28",searchAreaBg:"transparent",searchInputText:"search...",searchInputBg:"#cccccc",searchInputBorderColor:"#4a4a4a",searchInputTextColor:"#333333",topTitleColor:"#FFFFFF",timerColor:"#FFFFFF",bufferEmptyColor:"#929292",bufferFullColor:"#333333",seekbarColor:"#ffffff",volumeOffColor:"#454545",volumeOnColor:"#ffffff",isBufferInitialized:!1,isSeekBarInitialized:!1,playButColorOff:"#de1a21",playButColorOn:"#de1a21",youtubeJsUrl:"https://www.youtube.com/iframe_api",
vimeoJsUrl:"http://a.vimeocdn.com/js/froogaloop2.min.js",googleTrakingOn:!1,googleTrakingCode:"",origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origThumbImgW:69,origThumbImgH:69,origthumbLeftPadding:0,origthumbRightPadding:0,origthumbTopPadding:0,origthumbBottomPadding:0,origthumbTitleFont:0,origthumbRegFont:0,origthumbTitleLineHeight:0,origthumbRegLineHeight:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0,
isPlaylistSliderInitialized:!1}})(jQuery);
