/*
 * Multimedia - classic Carousel v1.3
 *
 * Copyright 2013-2017 LambertGroup
 * 
 */


(function(c){function B(a,b,m,l){c(".titlez",b).css({color:m,"font-size":a.titleFontSize/(a.origWidth/a.width)+"px","margin-top":a.titleMarginTop/(a.origWidth/a.width)+"px"});c(".descz",b).css({color:l,"font-size":a.descFontSize/(a.origWidth/a.width)+"px","margin-top":a.descMarginTop/(a.origWidth/a.width)+"px"})}function E(a,b,m,l,n,f,p,g,h,e,k,u,q,r,d,v,t,y){l=c("body").css("overflow");c("body").css("overflow","hidden");u.css("display","none");responsiveWidth=n.parent().parent().parent().width();
responsiveHeight=n.parent().parent().parent().height();b.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());b.width100Proc&&(b.width=responsiveWidth);b.height100Proc&&(b.height=responsiveHeight);b.origWidth>responsiveWidth||b.width100Proc?b.width=responsiveWidth:b.width100Proc||(b.width=b.origWidth);b.height100Proc||(b.height=b.width/a.bannerRatio);b.width=parseInt(b.width,10);b.height=parseInt(b.height,10);clearTimeout(a.timeoutID);D(a,b,m,p,v,q,
g,y,t,r,d,u,k);0<b.autoPlay&&m>b.numberOfThumbsPerScreen&&(a.timeoutID=setTimeout(function(){z(0,q,g,y,b,m,t,a,u,k)},1E3*b.autoPlay));if(b.showOnInitBottomNav)switch(h.css({bottom:parseInt(b.bottomNavMarginBottom/(b.origWidth/b.width))+"px",top:"auto"}),b.bottomNavPosition){case "left":h.css("left",g.width()+"px");break;case "middle":h.css("left",parseInt((p.width()-h.width())/2,10)+"px");break;case "right":h.css("left",b.width-y.width()-h.width()+"px");break;default:h.css("left",parseInt((p.width()-
bottomNavWidth)/2,10)+"px")}c("body").css("overflow",l)}function D(a,b,m,l,n,f,p,g,h,e,k,u,q){l.width(b.width);l.height(b.height);k.width(b.width);k.height(b.height);p.css({"margin-top":parseInt((b.height-p.height())/2,10)+"px",left:"0"});g.css({"margin-top":parseInt((b.height-g.height())/2,10)+"px",right:"0"});e.css("width",b.width-p.width()-g.width());e.height(b.height);b.origWidthThumbsHolderVisibleWrapper=b.origWidth-p.width()-g.width();newWidthThumbsHolderVisibleWrapper=e.width();b.responsive&&
b.origWidthThumbsHolderVisibleWrapper!=newWidthThumbsHolderVisibleWrapper&&newWidthThumbsHolderVisibleWrapper++;n.css({width:parseInt((b.imageWidth+2*b.itemPadding)/(b.origWidthThumbsHolderVisibleWrapper/newWidthThumbsHolderVisibleWrapper),10)+"px",height:b.height+"px"});c(".paddingx",n).css({padding:parseInt(b.itemPadding/(b.origWidthThumbsHolderVisibleWrapper/newWidthThumbsHolderVisibleWrapper),10)+"px"});B(b,f,b.titleColorOFF,b.descColorOFF);c(".thumbsHolder_ThumbOFF",l).find("img:first").css({width:n.width()-
2*parseInt(b.itemPadding/(b.origWidthThumbsHolderVisibleWrapper/newWidthThumbsHolderVisibleWrapper),10)+"px",height:parseInt(b.imageHeight/(b.origWidthThumbsHolderVisibleWrapper/newWidthThumbsHolderVisibleWrapper),10)+"px"});a.thumbMarginLeft=Math.floor((b.width-p.width()-g.width()-n.width()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1));n.css({"margin-left":a.thumbMarginLeft+"px"});f.css("width",(n.width()+a.thumbMarginLeft)*m-a.thumbMarginLeft+"px");f.children().first().css("margin-left",
"0px");b.numberOfThumbsPerScreen>=m&&e.css("left",parseInt((b.width-(n.width()+a.thumbMarginLeft)*m)/2,10)+parseInt(a.thumbMarginLeft/2,10)+"px");a.carouselStep=(n.width()+a.thumbMarginLeft)*b.numberOfThumbsPerScreen;f.css("left",-1*a.carouselStep*a.currentNavPage+"px")}function z(a,b,m,l,n,f,p,g,h,e){h.css({display:"none"});b.css("opacity","0.5");g.isCarouselScrolling=!0;c(e[g.currentNavPage]).removeClass("bottomNavButtonON");0!=a?g.currentNavPage+=a:g.currentNavPage==Math.ceil(f/n.numberOfThumbsPerScreen)-
1?g.currentNavPage=0:g.currentNavPage++;c(e[g.currentNavPage]).addClass("bottomNavButtonON");b.animate({opacity:1,left:-1*g.currentNavPage*g.carouselStep+"px"},500,"easeOutCubic",function(){F(g,b,m,l,n,f,p);g.isCarouselScrolling=!1;0<n.autoPlay&&f>n.numberOfThumbsPerScreen&&(clearTimeout(g.timeoutID),g.timeoutID=setTimeout(function(){z(0,b,m,l,n,f,p,g,h,e)},1E3*n.autoPlay))})}function F(a,c,m,l,n,f,p){currentCarouselLeft=c.css("left").substr(0,c.css("left").lastIndexOf("px"));0>currentCarouselLeft?
m.hasClass("carouselLeftNavDisabled")&&m.removeClass("carouselLeftNavDisabled"):m.addClass("carouselLeftNavDisabled");Math.abs(currentCarouselLeft-a.carouselStep)<(c.children().first().width()+a.thumbMarginLeft)*f?l.hasClass("carouselRightNavDisabled")&&l.removeClass("carouselRightNavDisabled"):l.addClass("carouselRightNavDisabled")}function G(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,
10)}c.multimedia_classic_carousel={version:"1.0"};c.fn.multimedia_classic_carousel=function(a){a=c.extend({},c.fn.multimedia_classic_carousel.defaults,a);return this.each(function(){function b(a,d,b){a.effectIsRunning||(a.isPrettyPhoto=!1,c(".thumbsHolder_ThumbOFF",f).mouseleave(),void 0!=c(b[a.current_img_no]).attr("data-link")&&""!=c(b[a.current_img_no]).attr("data-link")?(d=d.target,void 0!=c(b[a.current_img_no]).attr("data-target")&&""!=c(b[a.current_img_no]).attr("data-target")&&(d=c(b[a.current_img_no]).attr("data-target")),
"_blank"==d?window.open(c(b[a.current_img_no]).attr("data-link")):window.location=c(b[a.current_img_no]).attr("data-link")):void 0!=c(b[a.current_img_no]).attr("data-large-image")&&""!=c(b[a.current_img_no]).attr("data-large-image")?(a.isPrettyPhoto=!0,c.prettyPhoto.open(c(b[a.current_img_no]).attr("data-large-image"),c(".titlez",c(b[a.current_img_no])).html())):void 0!=c(b[a.current_img_no]).attr("data-video-youtube")&&""!=c(b[a.current_img_no]).attr("data-video-youtube")?(a.isPrettyPhoto=!0,c.prettyPhoto.open("https://www.youtube.com/watch?v="+
c(b[a.current_img_no]).attr("data-video-youtube"),c(".titlez",c(b[a.current_img_no])).html())):void 0!=c(b[a.current_img_no]).attr("data-video-vimeo")&&""!=c(b[a.current_img_no]).attr("data-video-vimeo")?(a.isPrettyPhoto=!0,c.prettyPhoto.open("https://www.vimeo.com/"+c(b[a.current_img_no]).attr("data-video-vimeo"),c(".titlez",c(b[a.current_img_no])).html())):void 0!=c(b[a.current_img_no]).attr("data-video-selfhosted")&&""!=c(b[a.current_img_no]).attr("data-video-selfhosted")?(a.isPrettyPhoto=!0,c.prettyPhoto.open(c(b[a.current_img_no]).attr("data-video-selfhosted")+
".mp4",c(".titlez",c(b[a.current_img_no])).html())):void 0!=c(b[a.current_img_no]).attr("data-audio")&&""!=c(b[a.current_img_no]).attr("data-audio")&&(a.isPrettyPhoto=!0,c.prettyPhoto.open(c(b[a.current_img_no]).attr("data-audio")+".mp3",c(".titlez",c(b[a.current_img_no])).html())));a.isPrettyPhoto&&clearTimeout(a.timeoutID)}var m=c(this);responsiveWidth=m.parent().width();responsiveHeight=m.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());
a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));a.width=parseInt(a.width,10);a.height=parseInt(a.height,10);var l=c("<div></div>").addClass("multimedia_classic_carousel").addClass(a.skin),n=c('<div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>   <div class="iconOver"></div>');
m.wrap(l);m.after(n);var f=m.parent(".multimedia_classic_carousel"),n=c(".bannerControls",f),p=c(".thumbsHolderWrapper",f),g=c(".thumbsHolderVisibleWrapper",f),h=c(".thumbsHolder",f);var e=c('<div class="carouselLeftNav"></div>');var k=c('<div class="carouselRightNav"></div>');p.append(e);p.append(k);e.css({"margin-top":parseInt((a.height-e.height())/2,10)+"px"});k.css({"margin-top":parseInt((a.height-k.height())/2,10)+"px",right:"0"});h.css("width","0px");l=c('<div class="bottomNav"></div>');m.after(l);
var u=c(".bottomNav",f);u.css("display","block");u.css({bottom:a.bottomNavMarginBottom+"px",top:"auto"});f.width(a.width);f.height(a.height);p.width(a.width);p.height(a.height);g.height(a.height);e.css("display","none");k.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(e.css("display","block"),k.css("display","block"));a.showBottomNav||u.css("display","none");a.showOnInitBottomNav||u.css("left","-5000px");var q=c(".iconOver",f);a.showNavArrows||(e.width(0),k.width(0));0==a.numberOfThumbsPerScreen&&
(a.numberOfThumbsPerScreen=Math.floor((a.origWidth-e.width()-k.width())/(a.imageWidth+2*a.itemPadding)));var r=0,d={current_img_no:0,currentImg:0,currentNavPage:0,prevNavPage:0,thumbMarginLeft:0,mouseOverBanner:!1,isCarouselScrolling:!1,carouselStep:0,isPrettyPhoto:!1,curIcon:"empty.png",timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,windowWidth:0,canvas:"",ctx:"",bannerRatio:a.origWidth/a.origHeight},v=m.find("ul:first").children(),t;d.thumbMarginLeft=Math.floor((a.origWidth-
e.width()-k.width()-(a.imageWidth+2*a.itemPadding)*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-1));var y=l=0;v.each(function(){d.currentImg=c(this);d.currentImg.is("li")||(d.currentImg=d.currentImg.find("li:first"));d.currentImg.is("li")&&(r++,t=c('<div class="thumbsHolder_ThumbOFF" rel="'+(r-1)+'"><div class="paddingx" style="padding:'+a.itemPadding+'px">'+d.currentImg.html()+"</div></div>"),h.append(t),t.css({width:a.imageWidth+2*a.itemPadding+"px",height:a.origHeight+"px"}),-1!=a.itemBackgroundColorOFF.lastIndexOf(".png")||
-1!=a.itemBackgroundColorOFF.lastIndexOf(".jpg")||-1!=a.itemBackgroundColorOFF.lastIndexOf(".gif")?t.css({background:"url("+a.itemBackgroundColorOFF+")"}):t.css({background:a.itemBackgroundColorOFF}),h.css("width",h.width()+d.thumbMarginLeft+(a.imageWidth+2*a.itemPadding)+"px"),1>=r?t.css("margin-left","0px"):t.css("margin-left",d.thumbMarginLeft+"px"));h.css("width",h.width()-d.thumbMarginLeft+"px")});g.css("width",g.width()-e.width()-k.width());g.css("left",e.width());d.carouselStep=(a.imageWidth+
2*a.itemPadding+d.thumbMarginLeft)*a.numberOfThumbsPerScreen;0===Math.floor(d.current_img_no/a.numberOfThumbsPerScreen)&&e.addClass("carouselLeftNavDisabled");Math.floor(d.current_img_no/a.numberOfThumbsPerScreen)==Math.floor(r/a.numberOfThumbsPerScreen)&&k.addClass("carouselRightNavDisabled");g.css({width:a.origWidth-e.width()-k.width(),left:e.width()+"px"});d.carouselStep=(a.imageWidth+2*a.itemPadding+d.thumbMarginLeft)*a.numberOfThumbsPerScreen;e.addClass("carouselLeftNavDisabled");a.numberOfThumbsPerScreen>=
r&&(k.addClass("carouselRightNavDisabled"),e.css("display","none"),k.css("display","none"),g.css("left",parseInt((p.width()-(a.imageWidth+2*a.itemPadding+d.thumbMarginLeft)*r)/2,10)+"px"));p.css("top",a.height+"px");c(".thumbsHolder_ThumbOFF",h).find("img:first").css({width:a.imageWidth+"px",height:a.imageHeight+"px"});B(a,h,a.titleColorOFF,a.descColorOFF);for(y=0;y<Math.ceil(r/a.numberOfThumbsPerScreen);y++){var A=c('<div class="bottomNavButtonOFF" rel="'+y+'"></div>');u.append(A);l+=parseInt(A.css("padding-left").substring(0,
A.css("padding-left").length-2),10)+A.width();A.css("margin-top","50px")}u.width(l);if(a.showOnInitBottomNav)switch(a.bottomNavPosition){case "left":u.css("left",e.width()+"px");break;case "middle":u.css("left",parseInt((f.width()-l)/2,10)+"px");break;case "right":u.css("left",a.width-k.width()-u.width()+"px");break;default:u.css("left",parseInt((f.width()-l)/2,10)+"px")}var w=c(".bottomNavButtonOFF",f),x=c(".thumbsHolder_ThumbOFF",f);D(d,a,r,f,x,h,e,k,t,g,p,q,w);x=c(".thumbsHolder_ThumbOFF",f);x.mousedown(function(){d.effectIsRunning||
c(this).attr("rel")});x.click(function(){b(d,a,v)});x.mouseenter(function(){-1!=a.itemBackgroundColorOFF.lastIndexOf(".png")||-1!=a.itemBackgroundColorOFF.lastIndexOf(".jpg")||-1!=a.itemBackgroundColorOFF.lastIndexOf(".gif")?x.css({background:"url("+a.itemBackgroundColorOFF+")"}):x.css({background:a.itemBackgroundColorOFF});var b=c(this);d.currentImg=b;d.current_img_no=b.attr("rel");-1!=a.itemBackgroundColorON.lastIndexOf(".png")||-1!=a.itemBackgroundColorON.lastIndexOf(".jpg")||-1!=a.itemBackgroundColorON.lastIndexOf(".gif")?
b.css({background:"url("+a.itemBackgroundColorON+")"}):b.css({background:a.itemBackgroundColorON});c(".titlez",b).css({color:a.titleColorON,"font-size":a.titleFontSize/(a.origWidth/a.width)+"px","margin-top":a.titleMarginTop/(a.origWidth/a.width)+"px"});c(".descz",b).css({color:a.descColorON,"font-size":a.descFontSize/(a.origWidth/a.width)+"px","margin-top":a.descMarginTop/(a.origWidth/a.width)+"px"});d.curIcon="empty.png";c(v[d.current_img_no]).attr("data-link")?d.curIcon="link.png":c(v[d.current_img_no]).attr("data-large-image")?
d.curIcon="image.png":c(v[d.current_img_no]).attr("data-video-youtube")||c(v[d.current_img_no]).attr("data-video-vimeo")||c(v[d.current_img_no]).attr("data-video-selfhosted")?d.curIcon="video.png":c(v[d.current_img_no]).attr("data-audio")&&(d.curIcon="audio.png");display_val="block";"empty.png"==d.curIcon&&(display_val="none");b=c(".thumbsHolder_ThumbOFF",f).find("img:first");q.css({left:d.current_img_no%a.numberOfThumbsPerScreen*x.width()+d.current_img_no%a.numberOfThumbsPerScreen*d.thumbMarginLeft+
parseInt((x.width()-q.width())/2,10)+e.width()+"px",top:parseInt((b.height()-q.height())/2,10)+"px",background:"url("+a.absUrl+"skins/"+a.skin+"/"+d.curIcon+")",display:display_val})});x.mouseleave(function(){var b=c(this);-1!=a.itemBackgroundColorOFF.lastIndexOf(".png")||-1!=a.itemBackgroundColorOFF.lastIndexOf(".jpg")||-1!=a.itemBackgroundColorOFF.lastIndexOf(".gif")?b.css({background:"url("+a.itemBackgroundColorOFF+")"}):b.css({background:a.itemBackgroundColorOFF});B(a,h,a.titleColorOFF,a.descColorOFF)});
e.click(function(){d.isCarouselScrolling||(d.isPrettyPhoto=!1,clearTimeout(d.timeoutID),currentCarouselLeft=h.css("left").substr(0,h.css("left").lastIndexOf("px")),0>currentCarouselLeft&&z(-1,h,e,k,a,r,t,d,q,w))});k.click(function(){d.isCarouselScrolling||(d.isPrettyPhoto=!1,clearTimeout(d.timeoutID),currentCarouselLeft=h.css("left").substr(0,h.css("left").lastIndexOf("px")),Math.abs(currentCarouselLeft-d.carouselStep)<(t.width()+d.thumbMarginLeft)*r&&z(1,h,e,k,a,r,t,d,q,w))});u.children().first().addClass("bottomNavButtonON");
w.mousedown(function(){if(!d.isCarouselScrolling){var b=c(this).attr("rel");b!=d.currentNavPage&&(d.isPrettyPhoto=!1,c(w[d.currentNavPage]).removeClass("bottomNavButtonON"),d.currentNavPage=b-1,z(0,h,e,k,a,r,t,d,q,w))}});w.mouseenter(function(){c(this).addClass("bottomNavButtonON")});w.mouseleave(function(){var a=c(this),b=a.attr("rel");d.currentNavPage!=b&&a.removeClass("bottomNavButtonON")});f.mouseenter(function(){d.isPrettyPhoto||(d.mouseOverBanner=!0,clearTimeout(d.timeoutID),a.autoHideNavArrows&&
a.showNavArrows&&(e.css("display","block"),k.css("display","block")))});f.mouseleave(function(){d.isPrettyPhoto||(d.mouseOverBanner=!1,d.curIcon="empty.png",q.css({background:"url("+a.absUrl+"skins/"+a.skin+"/"+d.curIcon+")",display:"none"}),q.css({display:"none"}),a.autoHideNavArrows&&a.showNavArrows&&(e.css("display","none"),k.css("display","none")),0<a.autoPlay&&r>a.numberOfThumbsPerScreen&&!d.isPrettyPhoto&&(clearTimeout(d.timeoutID),direction=-1,k.hasClass("carouselRightNavDisabled")&&(direction=
0),d.timeoutID=setTimeout(function(){z(0,h,e,k,a,r,t,d,q,w)},1E3*a.autoPlay)))});c.multimedia_classic_carousel.continueAutoplay=function(a){d.isPrettyPhoto=!1;f.mouseleave()};q.click(function(){b(d,a,v)});q.mouseenter(function(){c(".titlez",d.currentImg).css({color:a.titleColorON,"font-size":a.titleFontSize/(a.origWidth/a.width)+"px","margin-top":a.titleMarginTop/(a.origWidth/a.width)+"px"});c(".descz",d.currentImg).css({color:a.descColorON,"font-size":a.descFontSize/(a.origWidth/a.width)+"px","margin-top":a.descMarginTop/
(a.origWidth/a.width)+"px"});-1!=a.itemBackgroundColorON.lastIndexOf(".png")||-1!=a.itemBackgroundColorON.lastIndexOf(".jpg")||-1!=a.itemBackgroundColorON.lastIndexOf(".gif")?d.currentImg.css({background:"url("+a.itemBackgroundColorON+")"}):d.currentImg.css({background:a.itemBackgroundColorON})});a.enableTouchScreen&&f.swipe({swipe:function(b,f,g,h,l){d.effectIsRunning||(d.curIcon="empty.png",q.css({background:"url("+a.absUrl+"skins/"+a.skin+"/"+d.curIcon+")",display:"none"}),origLeft=c(this).css("left"),
q.css({display:"none"}),finalLeft=c(this).css("left"),"right"==f?e.hasClass("carouselLeftNavDisabled")||e.click():k.hasClass("carouselRightNavDisabled")||k.click(),c(this).css("left","0px"))}});var C=!1;c(window).resize(function(){var b=String(navigator.userAgent).toLowerCase();if(!d.isPrettyPhoto||"undefined"==String(c(v[d.current_img_no]).attr("data-video-selfhosted"))||-1!=b.indexOf("android")||-1!=b.indexOf("ipad")||-1!=b.indexOf("iphone")||-1!=b.indexOf("ipod")||-1!=b.indexOf("webos")){var l=
G();doResizeNow=!0;-1!=b.indexOf("android")&&(0==a.windowOrientationScreenSize0&&0==window.orientation&&(a.windowOrientationScreenSize0=c(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=c(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=c(window).height()),a.windowOrientationScreenSize0&&0==window.orientation&&c(window).width()>a.windowOrientationScreenSize0&&(doResizeNow=
!1),a.windowOrientationScreenSize90&&90==window.orientation&&c(window).height()>a.windowOrientationScreenSize90&&(doResizeNow=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&c(window).height()>a.windowOrientationScreenSize_90&&(doResizeNow=!1),0==d.windowWidth&&(doResizeNow=!1,d.windowWidth=c(window).width()));-1!=l&&9==l&&0==d.windowWidth&&(doResizeNow=!1);d.windowWidth==c(window).width()?(doResizeNow=!1,a.windowCurOrientation==window.orientation||-1==b.indexOf("android")&&-1==b.indexOf("ipad")&&
-1==b.indexOf("iphone")&&-1==b.indexOf("ipod")&&-1==b.indexOf("webos")||(a.windowCurOrientation=window.orientation,doResizeNow=!0)):d.windowWidth=c(window).width();a.responsive&&doResizeNow?(!1!==C&&clearTimeout(C),d.isPrettyPhoto&&c.prettyPhoto.close(),C=setTimeout(function(){E(d,a,r,v,m,n,f,e,u,A,w,q,h,g,p,x,t,k)},300)):doResizeNow&&d.isPrettyPhoto&&c.prettyPhoto.close()}});l=f.find("img:first");l[0].complete?(c(".myloader",f).css("display","none"),0<a.autoPlay&&r>a.numberOfThumbsPerScreen&&(d.timeoutID=
setTimeout(function(){z(0,h,e,k,a,r,t,d,q,w)},1E3*a.autoPlay))):l.load(function(){c(".myloader",f).css("display","none");0<a.autoPlay&&r>a.numberOfThumbsPerScreen&&(d.timeoutID=setTimeout(function(){z(0,h,e,k,a,r,t,d,q,w)},1E3*a.autoPlay))})})};c.fn.multimedia_classic_carousel.defaults={skin:"black",width:960,height:384,width100Proc:!1,height100Proc:!1,autoPlay:4,numberOfThumbsPerScreen:0,itemPadding:5,target:"_blank",showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!1,showBottomNav:!0,showOnInitBottomNav:!0,
autoHideBottomNav:!0,enableTouchScreen:!0,absUrl:"",itemBackgroundColorOFF:"#CCCCCC",itemBackgroundColorON:"#CCCCCC",titleColorOFF:"#000000",descColorOFF:"#333333",titleColorON:"#FF0000",descColorON:"#000000",titleFontSize:20,descFontSize:14,titleMarginTop:5,descMarginTop:8,imageWidth:452,imageHeight:302,responsive:!1,responsiveRelativeToBrowser:!0,bottomNavMarginBottom:0,bottomNavPosition:"right",origWidth:0,origHeight:0,origWidthThumbsHolderVisibleWrapper:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,
windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);